[[GCCBootstrapMacOS]]
arch = "x86_64"
git-tree-sha1 = "3a6260d564c37985da1005e4f5a9fd5e668834b5"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapMacOS.download]]
    sha256 = "baea2c5b1f0815af51e0f4cbfc62d65748fb3ef5be43f35d498313e952431db6"
    url = "https://github.com/staticfloat/GCCBootstrapMacOS_jll.jl/releases/download/v14.2.0/GCCBootstrapMacOS-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapMacOS]]
arch = "x86_64"
git-tree-sha1 = "51ed16989be74a27ef53a1774438ce51d0981093"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapMacOS.download]]
    sha256 = "72b4421c303e720a8de7c824f8eb509fad4131dc7b37a5a69830cd4a3a7b91f0"
    url = "https://github.com/staticfloat/GCCBootstrapMacOS_jll.jl/releases/download/v14.2.0/GCCBootstrapMacOS-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"

[[GCCBootstrapMacOS-build_log]]
arch = "x86_64"
git-tree-sha1 = "2d152c42e3b98cc1fba37543c8cfbce0cced6adc"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapMacOS-build_log.download]]
    sha256 = "bd7388dbe800e8bdc885d3b31f54bd0bccb1e557dbbe0bb4de908b4da2ef64c3"
    url = "https://github.com/staticfloat/GCCBootstrapMacOS_jll.jl/releases/download/v14.2.0/GCCBootstrapMacOS-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapMacOS-build_log]]
arch = "x86_64"
git-tree-sha1 = "b4b9a72466668b44b6813a934f356f63af30a98c"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapMacOS-build_log.download]]
    sha256 = "ba5a134a781726868c9565deb38cb147d96438970d0e02b47b74b325abc2c5a2"
    url = "https://github.com/staticfloat/GCCBootstrapMacOS_jll.jl/releases/download/v14.2.0/GCCBootstrapMacOS-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"

[[GCCBootstrapMacOS-extract_log]]
arch = "x86_64"
git-tree-sha1 = "fe473fc66184ead545ebf1528ea57d0d071ceb7e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapMacOS-extract_log.download]]
    sha256 = "72803356866bd697fc50f720d8d346fb6c67940b96702f496436ae8f73eaec0c"
    url = "https://github.com/staticfloat/GCCBootstrapMacOS_jll.jl/releases/download/v14.2.0/GCCBootstrapMacOS-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapMacOS-extract_log]]
arch = "x86_64"
git-tree-sha1 = "39b430c68bd7fc6f9ec2681d7aaf7cdfa26d7e2e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapMacOS-extract_log.download]]
    sha256 = "aef39599932c2c99ffd2d0b8e27a1ceff8b33e1fe8758ec622a1a0a0689ca3ed"
    url = "https://github.com/staticfloat/GCCBootstrapMacOS_jll.jl/releases/download/v14.2.0/GCCBootstrapMacOS-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
